### PR TITLE
Profile datatype fixes and restrict dynamic profile endpoints to finalised versions

### LINKED ISSUE #213: Cannot add a profile, with a data type I have added, to a model
**Describe the bug**
Get a ```java.lang.NullPointerException: Cannot get property 'label' on null object```when applying a profile which includes a Data Type I have added

**To Reproduce**
1. Create a new Data Model, adding the Profile Specification Data Types, and adding the Profile Specification Profile.
2. Add a Data Class to the profile
3. Add a Data Element to the Data Class, but rather than using one of the existing Data Types that was added in step 1, create a new Data Type e.g. 'Custom'
4. Save the profile
5. Navigate to a different Model (e.g. any Data Model, CodeSet etc..) and try to add the profile created above.
6. In the UI, see an error 'There was a problem getting the expected profile'. and in the logs a ```java.lang.NullPointerException: Cannot get property 'label' on null object```

**Expected behavior**
Expect to be able to add the profile, with the Data Type I added, to another model

**Screenshots**
```
java.lang.NullPointerException: Cannot get property 'label' on null object
        at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.callGetProperty(GetEffectivePogoPropertySite.java:45)
        at mdm_testing_functional_profileField__profileField_gson$_run_closure1.doCall(mdm_testing_functional_profileField__profileField_gson:15)
        at mdm_testing_functional_profileField__profileField_gson$_run_closure1.call(mdm_testing_functional_profileField__profileField_gson)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.cloneDelegateAndGetContent(StreamingJsonBuilder.java:837)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.access$000(StreamingJsonBuilder.java:501)
        at grails.plugin.json.builder.StreamingJsonBuilder.call(StreamingJsonBuilder.java:255)
        at grails.plugin.json.view.JsonViewWritableScript.json(JsonViewWritableScript.groovy:72)
        at mdm_testing_functional_profileField__profileField_gson.run(mdm_testing_functional_profileField__profileField_gson:7)
```

**Additional context**
At

https://github.com/MauroDataMapper/mdm-core/blob/3c63a679be62ddf9aa9ce0852f7baad047f08eec/mdm-plugin-profile/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/profile/domain/ProfileFieldDataType.groovy#L51

the find fails to retrieve the Data Type because the label (e.g. 'Custom') does not match any of the values enumerated in ProfileFieldDataType. So a null value for dataType is propagated through to the response, which causes the exception when the view template is rendered.

### LINKED ISSUE #290: Error validating date field in profile
# Description

Validating a date as part of a submitted profile gives an error.

# Steps to reproduce

1. Create a dynamic profile containing a `date` type element
2. Attempt to validate the profile against a model using the UI
3. The date field will not validate

# Expected behavior

Dates in configured formats should validate

# Environment

Please complete the following information:
- mdm-core latest develop

# Additional context

Issue is with retrieving date formats from API properties, see mdm-plugin-profile BootStrap.groovy line 64.

### LINKED ISSUE #292: Error retrieving default version of profile for dynamic profile with non-finalised version
# Description

When the default version endpoint (`/api/dataModels/{id}/profile/uk.ac.ox.softeng.maurodatamapper.profile.provider/{profileLabel}`) for a dynamic profile is called for a dynamic profile with a finalised model version and a non-finalised model version, an error occurs.

# Steps to reproduce

1. Create a dynamic profile specification model and finalise it.
2. Apply the dynamic profile to a data model.
3. Create a new version of the dynamic profile specification model.
4. Using the UI, attempt to view the dynamic profile added to the data model in 2. An error occurs:
```json
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "OK",
  "url": "http://localhost:8080/api/dataModels/a010c5b0-05f0-4aed-8038-bf389bf039c3/profile/uk.ac.ox.softeng.maurodatamapper.profile.provider/Dynamic%20Profile%201",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for http://localhost:8080/api/dataModels/a010c5b0-05f0-4aed-8038-bf389bf039c3/profile/uk.ac.ox.softeng.maurodatamapper.profile.provider/Dynamic%20Profile%201: 500 OK",
  "error": {
    "status": 500,
    "reason": "Internal Server Error",
    "errorCode": "UEX--",
    "message": "Version 'SNAPSHOT' does not match the expected pattern",
    "path": "/api/dataModels/a010c5b0-05f0-4aed-8038-bf389bf039c3/profile/uk.ac.ox.softeng.maurodatamapper.profile.provider/Dynamic%20Profile%201",
    "environment": "DEVELOPMENT",
    "version": "5.1.0-SNAPSHOT",
    "exception": {
      "type": "IllegalStateException",
      "message": "Version 'SNAPSHOT' does not match the expected pattern",
      "stacktrace": [
        "jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)",
        "jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)",
        "uk.ac.ox.softeng.maurodatamapper.version.Version.from(Version.groovy:96)",
        "uk.ac.ox.softeng.maurodatamapper.provider.MauroDataMapperService.sortableVersion(MauroDataMapperService.groovy:63)",
        "uk.ac.ox.softeng.maurodatamapper.provider.MauroDataMapperService.compareTo(MauroDataMapperService.groovy:95)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "uk.ac.ox.softeng.maurodatamapper.profile.ProfileService.$tt__findProfileProviderService(ProfileService.groovy:78)",
        "jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)",
        "org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)",
        "grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)",
        "uk.ac.ox.softeng.maurodatamapper.profile.ProfileInterceptor.checkActionAuthorisationOnUnsecuredResource(ProfileInterceptor.groovy:77)",
        "uk.ac.ox.softeng.maurodatamapper.core.interceptor.FacetInterceptor.checkActionAllowedOnFacet(FacetInterceptor.groovy:76)",
        "uk.ac.ox.softeng.maurodatamapper.profile.ProfileInterceptor.before(ProfileInterceptor.groovy:40)",
        "org.grails.plugins.web.interceptors.GrailsInterceptorHandlerInterceptorAdapter.preHandle(GrailsInterceptorHandlerInterceptorAdapter.groovy:77)",
        "org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148)",
        "org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1062)",
        "org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)",
        "org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)",
        "org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)",
        "org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)",
        "org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)",
        "org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)",
        "java.lang.Thread.run(Thread.java:833)"
      ]
    }
  }
}
```

# Expected behavior

As only finalised models can define a dynamic profile, the default dynamic profile version should be the highest finalised version.

# Environment

- mdm-core latest develop

### PR DESCRIPTION
**Pull request by joe-crawford**
- Treat custom datatypes in profiles as strings (resolves #213)
- Fix to loading date formats from ApiProperties (resolves #290)
- Use finalised dynamic profile as default version (resolves #292), restrict dynamic profiles to finalised only in profile providers endpoint, sort profile provider endpoints
- Show only latest versions (by metadata namespace) of unused profiles by default, add latest versions (by metadata namespace) param to unused and used profile endpoints

### CODE REVIEW

**Comment by joe-crawford** [comment]
Failing branch test looks like a timing issue.

PR includes PR #287.

File: mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy [hunk 1]
```diff
@@ -50,11 +50,11 @@ class ProfileController implements ResourcelessMdmController, DataBinder {
 
 
     def profileProviders() {
-        respond profileProviderServices: profileService.getAllProfileProviderServices()
+        respond profileProviderServices: profileService.getAllProfileProviderServices(true).sort()
```
Comment (olliefreeman) [inline mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy:53]: it would be much cleaner for all these service methods to actually perform the cleaning rather than the controller asking for it, this makes sure that whoever calls the methods always gets the data in the format we would prefer...which in this situation is sorted...this comment applies to all changes in this file

**Review by olliefreeman — CHANGES_REQUESTED** [review]
wrt 290 and the not set fields... wow how did i miss that one! bug fail on me

ProfileService -> in 99% of situations where we call any method with the param finalisedOnly we're passing "true" therefore really the default to this param should now be true and the 1 location where we seem to asking for "false" (ProfileController nonProfileMetadata) should be where we pass a param of false...this is a much cleaner approach

**Comment by olliefreeman** [comment]
Note to self....need #287 merged first unless this branch is rebased off `feature/gh-277` and onto `develop`

File: mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy (hunk 1 above)
Comment (joe-crawford) [reply mdm-plugin-profile/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/profile/ProfileController.groovy]: Have changed the ProfileService methods to sort by version, and (for dynamic profiles) to restrict to finalised profile versions by default (via change in underlying `getAllProfileProviderServices` service method).

**Comment by joe-crawford** [comment]
PR has been rebased onto #287 and includes change from review of that PR.

**Review by olliefreeman — APPROVED** [review]
Im happy with this.

As a word of note (and it doesnt matter for this case, but will for larger domains) using the "only validate these fields" in the  Validateable class is dangerous for larger domains. The reason is that it infact validates the entire domain and then removes all field errors which dont match the requested fields. 
Therefore in this case its fine as the domain is small and its not doing any complicated validation, but beware in larger domains with more complex valdiation as its will cascade the validation .
